{% set version = "0.2.1" %}

package:
  name: ipyregulartable
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipyregulartable/ipyregulartable-{{ version }}.tar.gz
  sha256: 27a074a386139316c89ad1969f8225ca298688837182ddccb93498805ca5bb15

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cd js && yarn --production && yarn licenses generate-disclaimer > ../JS_LICENSES

requirements:
  build:
    - nodejs 18.*
    - yarn <2
  host:
    - jupyter-packaging
    - pip
    - python {{ python_min }}
  run:
    - ipywidgets >=7.5.1
    - numpy
    - pandas >=0.22
    - python >={{ python_min }}

test:
  imports:
    - ipyregulartable
    - ipyregulartable.datamodel
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jpmorganchase/ipyregulartable
  summary: ipywidgets wrapper around regular-table
  license: Apache-2.0
  license_file:
    - LICENSE
    - JS_LICENSES

extra:
  recipe-maintainers:
    - bollwyvl
    - timkpaine
