{% set name = "ipyregulartable" %}
{% set version = "0.2.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyregulartable-{{ version }}.tar.gz
  sha256: 27a074a386139316c89ad1969f8225ca298688837182ddccb93498805ca5bb15

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps
    - cd js && yarn --production && yarn licenses generate-disclaimer > ../JS_LICENSES

requirements:
  build:
    - yarn
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7.5.1
    - numpy
    - pandas >=0.22
    - python >=3.6

test:
  imports:
    - ipyregulartable
    - ipyregulartable.datamodel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpmorganchase/ipyregulartable
  summary: ipywidgets wrapper around regular-table
  license: Apache-2.0
  license_file:
    - LICENSE
    - JS_LICENSES

extra:
  recipe-maintainers:
    - bollwyvl
    - timkpaine
