# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.2.1"
  python_check_max: "3.14"

package:
  name: ipyregulartable
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/i/ipyregulartable/ipyregulartable-${{ version }}.tar.gz
  sha256: 27a074a386139316c89ad1969f8225ca298688837182ddccb93498805ca5bb15

build:
  number: 2
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cd js && yarn --production && yarn licenses generate-disclaimer > ../JS_LICENSES

requirements:
  build:
    - nodejs >=24,<25
    - yarn <2
  host:
    - jupyter-packaging
    - pip
    - python ${{ python_min }}.*
  run:
    - ipywidgets >=7.5.1
    - numpy
    - pandas >=0.22
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - ipyregulartable
        - ipyregulartable.datamodel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: ipywidgets wrapper around regular-table
  license: Apache-2.0
  license_file:
    - LICENSE
    - JS_LICENSES
  homepage: https://pypi.org/project/ipyregulartable
  repository: https://github.com/jpmorganchase/ipyregulartable

extra:
  recipe-maintainers:
    - bollwyvl
    - timkpaine
